### ISSUE TITLE
Question about Flink images

### ISSUE THREAD

**Issue by imalik8088** [ronlut/flink-k8s#2]
Hi @ronlut, 
thanks for sharing and arguing agains the approach Job vs Deployment in your blogpost. 

You have used an alpine image and installed flink on it... did also considered to use official flink images like for e.g. https://hub.docker.com/_/flink?tab=tags&page=1&name=1.9.2. The current Dockerfile/build.sh is quite verbose this would make the things less verbose.

Did you look into these images, are there also suitable or do you have any idea/input for that. Would like to use them instead...

**Comment by ronlut** [comment]
Hi @imalik8088, thanks :)

That's a good point.
I don't see a real reason not to build on top of the existing flink docker images.
But I don't see a good reason to do it as well - let me explain:

My current approach is based on [this section in flink docs](https://ci.apache.org/projects/flink/flink-docs-release-1.9/ops/deployment/kubernetes.html#creating-the-job-specific-image) - this is stated in the [README](https://github.com/ronlut/flink-k8s/blob/master/build-image/README.md) as well.
The docker images you are referring are [used in flink documentation for docker-compose deployment](https://ci.apache.org/projects/flink/flink-docs-release-1.9/ops/deployment/docker.html).

To use the dockerhub images you will need to add your job artifacts, as well as install and set python if you need to and probably use the `docker-entrypoint.sh` I use here, as they are are quite different and the dockerhub ones doesn't support job-cluster if i'm not mistaken (look for `standalone-job.sh` in the dockerhub entrypoint).
In addition, the kubernetes approach uses alpine as you correctly pointed out, which is a big advantage in image size.

Anyway, to use the dockerhub images you will need to have a Dockerfile similar to this (didn't check):
```
FROM flink:1.9.2-scala_2.12

# Flink environment variables
ENV FLINK_LIB_DIR $FLINK_HOME/lib
ENV FLINK_JOB_ARTIFACTS_DIR /opt/artifacts

ARG job_artifacts=NOT_SET

ADD $job_artifacts/* $FLINK_JOB_ARTIFACTS_DIR/

RUN set -x && \
  for jar in $FLINK_JOB_ARTIFACTS_DIR/*.jar; do [ -f "$jar" ] || continue; ln -s $jar $FLINK_LIB_DIR; done && \
  chown -R flink:flink ${FLINK_JOB_ARTIFACTS_DIR}/ && \

# override existing entrypoint
COPY docker-entrypoint.sh /
```

Let me know what you think.

P.S. edited your dockerhub link to v1.9.2 as my repo uses this version of flink (this might prevent confusion for future users).

**Comment by imalik8088** [comment]
Thanks for the in depth feedback.  

I've also started with [the official docs](https://ci.apache.org/projects/flink/flink-docs-release-1.9/ops/deployment/kubernetes.html#creating-the-job-specific-image) to convert a Flink app which was running on AWS EMR to k8s but found them as mentioned very verbose and to download in CI build each time a flink release is not a thing what I would to suggest to somebody or also to [install something](https://github.com/apache/flink/blob/release-1.9/flink-container/docker/Dockerfile#L22) basing packages each commit/push on a CI this makes the things harder (company proxies, packages are updated in background and are not stick a specific version, ...) 

>.... as well as install and set python if you need to and....

Yes agree the down side is that the docker images from dockerhub are not supporting python yet.

> .... dockerhub ones doesn't support job-cluster if i'm not mistaken ....

[also right](https://github.com/apache/flink-docker/blob/master/1.9/scala_2.11-debian/docker-entrypoint.sh#L95) the official images are starting Jobmanager with `jobmanager.sh` instead of `standalone-job.sh`

The official images are also using [alpine images](https://github.com/apache/flink-docker/blob/master/1.9/scala_2.11-debian/Dockerfile#L19)

Currently I'm using the same verbose approach but I think I would like to change it for the long term, so that other developer could understand it easier and less code to maintain by the team/developer.

**Comment by ronlut** [comment]
I agree that Flink's current flow is not perfect, but I prefer it on the dockerhub one which isn't perfect as well.
Hopefully we will have a better official/community solution in the near future.

Closing for now, you are welcome to reopen to discuss any new thoughts you might have regarding this topic!
